# -*- coding: utf-8 -*-
"""B22CS001_ass_4_tuned_en_to_hi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KdMjpuxzsK9hCCXuLi63UfKW-UNfm04S

#Part-1: Baseline Code
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the TSV dataset
df = pd.read_csv('English-Hindi.tsv', sep='\t', header=None, names=["id1", "en", "id2", "hi"])

# Show a sample
df.sample(5)

# Keep only the English and Hindi columns
df = df[["en", "hi"]]

# Drop any rows with missing data
df.dropna(inplace=True)

# Reset index
df.reset_index(drop=True, inplace=True)

# Preview cleaned data
df.head()

# Number of sentence pairs
print("Total pairs:", len(df))

# Sentence length distributions
df["en_len"] = df["en"].apply(lambda x: len(x.split()))
df["hi_len"] = df["hi"].apply(lambda x: len(x.split()))

print("\nEnglish Sentence Length Stats:")
print(df["en_len"].describe())

print("\nHindi Sentence Length Stats:")
print(df["hi_len"].describe())

plt.figure(figsize=(12, 5))

# English
plt.subplot(1, 2, 1)
sns.histplot(df["en_len"], bins=30, kde=True, color='skyblue')
plt.title("English Sentence Lengths")
plt.xlabel("Words")

# Hindi
plt.subplot(1, 2, 2)
sns.histplot(df["hi_len"], bins=30, kde=True, color='salmon')
plt.title("Hindi Sentence Lengths")
plt.xlabel("Words")

plt.tight_layout()
plt.show()

for i in range(5):
    print(f"EN: {df.loc[i, 'en']}")
    print(f"HI: {df.loc[i, 'hi']}")
    print("---")

def tokenize(sentence):
    return sentence.lower().strip().split()

from collections import Counter
import itertools

class Vocabulary:
    def __init__(self, freq_threshold=2):
        self.freq_threshold = freq_threshold
        self.itos = {0: "<pad>", 1: "<sos>", 2: "<eos>", 3: "<unk>"}
        self.stoi = {"<pad>": 0, "<sos>": 1, "<eos>": 2, "<unk>": 3}
        self.idx = 4

    def build_vocab(self, sentence_list):
        frequencies = Counter()
        for sentence in sentence_list:
            for word in self.tokenize(sentence):
                frequencies[word] += 1

        for word, freq in frequencies.items():
            if freq >= self.freq_threshold:
                self.stoi[word] = self.idx
                self.itos[self.idx] = word
                self.idx += 1

    def tokenize(self, sentence):
        return sentence.lower().strip().split()

    def numericalize(self, sentence):
        tokens = self.tokenize(sentence)
        return [self.stoi.get(token, self.stoi["<unk>"]) for token in tokens]

    def __len__(self):
        return len(self.stoi)

    def __getitem__(self, token):
        return self.stoi.get(token, self.stoi["<unk>"])

# Create vocab instances
en_vocab = Vocabulary(freq_threshold=2)
hi_vocab = Vocabulary(freq_threshold=2)

# Build vocabs
en_vocab.build_vocab(df["en"].tolist())
hi_vocab.build_vocab(df["hi"].tolist())

print(f"English vocab size: {len(en_vocab.stoi)}")
print(f"Hindi vocab size: {len(hi_vocab.stoi)}")

def encode_sentence(sentence, vocab, max_len=50):
    tokens = [vocab.stoi["<sos>"]] + vocab.numericalize(sentence)[:max_len-2] + [vocab.stoi["<eos>"]]
    return tokens + [vocab.stoi["<pad>"]] * (max_len - len(tokens))

sample_en = "That won't happen."
sample_hi = "वैसा नहीं होगा।"

print("Encoded English:", encode_sentence(sample_en, en_vocab))
print("Encoded Hindi:", encode_sentence(sample_hi, hi_vocab))

import torch
import torch.nn as nn
import math

class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=5000):
        super().__init__()

        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len).unsqueeze(1).float()
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))

        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)

        pe = pe.unsqueeze(0)  # (1, max_len, d_model)
        self.register_buffer('pe', pe)

    def forward(self, x):
        return x + self.pe[:, :x.size(1)]

def scaled_dot_product(q, k, v, mask=None):
    d_k = q.size(-1)
    scores = torch.matmul(q, k.transpose(-2, -1)) / math.sqrt(d_k)

    if mask is not None:
        scores = scores.masked_fill(mask == 0, -1e9)

    attention = torch.softmax(scores, dim=-1)
    return torch.matmul(attention, v), attention

class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, num_heads):
        super(MultiHeadAttention, self).__init__()
        assert d_model % num_heads == 0, "d_model must be divisible by num_heads"

        self.d_model = d_model
        self.num_heads = num_heads
        self.d_k = d_model // num_heads

        self.query_linear = nn.Linear(d_model, d_model)
        self.key_linear = nn.Linear(d_model, d_model)
        self.value_linear = nn.Linear(d_model, d_model)

        self.out_linear = nn.Linear(d_model, d_model)
        self.dropout = nn.Dropout(0.1)

    def forward(self, q, k, v, mask=None):
        batch_size = q.size(0)

        # Project Q, K, V
        Q = self.query_linear(q)  # [B, T, D]
        K = self.key_linear(k)
        V = self.value_linear(v)

        # Reshape and transpose: [B, T, D] -> [B, H, T, Dk]
        Q = Q.view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)  # [B, H, T, Dk]
        K = K.view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)
        V = V.view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)

        # Apply scaled dot-product attention
        scores = torch.matmul(Q, K.transpose(-2, -1)) / (self.d_k ** 0.5)

        if mask is not None:
            scores = scores.masked_fill(mask == 0, -1e9)

        attention_weights = torch.softmax(scores, dim=-1)
        attention_output = torch.matmul(self.dropout(attention_weights), V)  # [B, H, T, Dk]

        # Concatenate heads: [B, H, T, Dk] -> [B, T, H * Dk]
        attention_output = attention_output.transpose(1, 2).contiguous() \
                                            .view(batch_size, -1, self.d_model)

        return self.out_linear(attention_output)

class FeedForward(nn.Module):
    def __init__(self, d_model, d_ff=2048, dropout=0.1):
        super().__init__()
        self.linear1 = nn.Linear(d_model, d_ff)
        self.linear2 = nn.Linear(d_ff, d_model)
        self.dropout = nn.Dropout(dropout)
        self.relu = nn.ReLU()

    def forward(self, x):
        return self.linear2(self.dropout(self.relu(self.linear1(x))))

class LayerNorm(nn.Module):
    def __init__(self, d_model, eps=1e-6):
        super().__init__()
        self.gamma = nn.Parameter(torch.ones(d_model))
        self.beta = nn.Parameter(torch.zeros(d_model))
        self.eps = eps

    def forward(self, x):
        mean = x.mean(-1, keepdim=True)
        std = x.std(-1, keepdim=True)
        return self.gamma * (x - mean) / (std + self.eps) + self.beta

class EncoderLayer(nn.Module):
    def __init__(self, d_model, num_heads, d_ff, dropout=0.1):
        super().__init__()
        self.self_attn = MultiHeadAttention(d_model, num_heads)
        self.ffn = FeedForward(d_model, d_ff, dropout)
        self.norm1 = LayerNorm(d_model)
        self.norm2 = LayerNorm(d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, mask=None):
        x = self.norm1(x + self.dropout(self.self_attn(x, x, x, mask)))
        x = self.norm2(x + self.dropout(self.ffn(x)))
        return x

class DecoderLayer(nn.Module):
    def __init__(self, d_model, num_heads, d_ff, dropout=0.1):
        super().__init__()
        self.self_attn = MultiHeadAttention(d_model, num_heads)
        self.cross_attn = MultiHeadAttention(d_model, num_heads)
        self.ffn = FeedForward(d_model, d_ff, dropout)

        self.norm1 = LayerNorm(d_model)
        self.norm2 = LayerNorm(d_model)
        self.norm3 = LayerNorm(d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, enc_out, src_mask=None, tgt_mask=None):
        x = self.norm1(x + self.dropout(self.self_attn(x, x, x, tgt_mask)))
        x = self.norm2(x + self.dropout(self.cross_attn(x, enc_out, enc_out, src_mask)))
        x = self.norm3(x + self.dropout(self.ffn(x)))
        return x

class Encoder(nn.Module):
    def __init__(self, input_vocab_size, d_model, num_layers, num_heads, d_ff, max_len, dropout=0.1):
        super().__init__()
        self.embed = nn.Embedding(input_vocab_size, d_model)
        self.pos_enc = PositionalEncoding(d_model, max_len)
        self.layers = nn.ModuleList([
            EncoderLayer(d_model, num_heads, d_ff, dropout)
            for _ in range(num_layers)
        ])
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, mask=None):
        x = self.embed(x)
        x = self.pos_enc(x)
        x = self.dropout(x)

        for layer in self.layers:
            x = layer(x, mask)

        return x

class Decoder(nn.Module):
    def __init__(self, target_vocab_size, d_model, num_layers, num_heads, d_ff, max_len, dropout=0.1):
        super().__init__()
        self.embed = nn.Embedding(target_vocab_size, d_model)
        self.pos_enc = PositionalEncoding(d_model, max_len)
        self.layers = nn.ModuleList([
            DecoderLayer(d_model, num_heads, d_ff, dropout)
            for _ in range(num_layers)
        ])
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, enc_out, src_mask=None, tgt_mask=None):
        x = self.embed(x)
        x = self.pos_enc(x)
        x = self.dropout(x)

        for layer in self.layers:
            x = layer(x, enc_out, src_mask, tgt_mask)

        return x

class Transformer(nn.Module):
    def __init__(self, src_vocab_size, tgt_vocab_size, d_model=512, num_layers=6, num_heads=8, d_ff=2048, max_len=100, dropout=0.1):
        super().__init__()
        self.encoder = Encoder(src_vocab_size, d_model, num_layers, num_heads, d_ff, max_len, dropout)
        self.decoder = Decoder(tgt_vocab_size, d_model, num_layers, num_heads, d_ff, max_len, dropout)
        self.fc_out = nn.Linear(d_model, tgt_vocab_size)

    def make_pad_mask(self, seq, pad_idx):
        return (seq != pad_idx).unsqueeze(1).unsqueeze(2)  # [B, 1, 1, T]

    def make_subsequent_mask(self, size):
        return torch.tril(torch.ones((size, size))).bool().to(next(self.parameters()).device)

    def forward(self, src, tgt, src_pad_idx, tgt_pad_idx):
        src_mask = self.make_pad_mask(src, src_pad_idx)
        tgt_pad_mask = self.make_pad_mask(tgt, tgt_pad_idx)
        tgt_sub_mask = self.make_subsequent_mask(tgt.size(1))
        tgt_mask = tgt_pad_mask & tgt_sub_mask  # Combine masks

        enc_out = self.encoder(src, src_mask)
        dec_out = self.decoder(tgt, enc_out, src_mask, tgt_mask)

        out = self.fc_out(dec_out)
        return out

from torch.utils.data import Dataset

class TranslationDataset(Dataset):
    def __init__(self, df, en_vocab, hi_vocab, max_len=50):
        self.en_sentences = df["en"].tolist()
        self.hi_sentences = df["hi"].tolist()
        self.en_vocab = en_vocab
        self.hi_vocab = hi_vocab
        self.max_len = max_len

    def __len__(self):
        return len(self.en_sentences)

    def __getitem__(self, idx):
        src = encode_sentence(self.en_sentences[idx], self.en_vocab, self.max_len)
        tgt = encode_sentence(self.hi_sentences[idx], self.hi_vocab, self.max_len)
        return torch.tensor(src), torch.tensor(tgt)

def collate_fn(batch):
    src_batch, tgt_batch = zip(*batch)

    src_batch = torch.stack(src_batch)
    tgt_batch = torch.stack(tgt_batch)

    # Transformer decoder needs: tgt_input (without <eos>) and tgt_output (without <sos>)
    tgt_input = tgt_batch[:, :-1]
    tgt_output = tgt_batch[:, 1:]

    return src_batch, tgt_input, tgt_output

from torch.utils.data import DataLoader

BATCH_SIZE = 60
MAX_LEN = 50

dataset = TranslationDataset(df, en_vocab, hi_vocab, max_len=MAX_LEN)
train_loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_fn)

import torch.nn as nn
import torch.optim as optim
from tqdm import tqdm

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using Device: {DEVICE}")

# Hyperparams
SRC_PAD_IDX = en_vocab["<pad>"]
TGT_PAD_IDX = hi_vocab["<pad>"]
NUM_EPOCHS = 100
D_MODEL = 512

model = Transformer(
    src_vocab_size=len(en_vocab),
    tgt_vocab_size=len(hi_vocab),
    d_model=D_MODEL,
    num_layers=6,
    num_heads=8,
    d_ff=2048,
    max_len=MAX_LEN,
    dropout=0.1
).to(DEVICE)

criterion = nn.CrossEntropyLoss(ignore_index=TGT_PAD_IDX)
optimizer = optim.Adam(model.parameters(), lr=1e-4)

import os

def save_checkpoint(epoch, model, optimizer, loss, path="checkpoint.pt"):
    torch.save({
        'epoch': epoch,
        'model_state': model.state_dict(),
        'optimizer_state': optimizer.state_dict(),
        'loss': loss
    }, path)

    print(f"Checkpoint saved at epoch {epoch}, loss {loss:.4f}.")

import torch

def load_checkpoint(model, optimizer, path="checkpoint.pt"):
    if torch.cuda.is_available() and path is not None and os.path.exists(path):
        checkpoint = torch.load(path)
    elif path is not None and os.path.exists(path):
        checkpoint = torch.load(path, map_location=torch.device('cpu'))
    else:
        print(f"No checkpoint found at {path}. Starting from scratch.")
        return 0

    model.load_state_dict(checkpoint['model_state'])
    optimizer.load_state_dict(checkpoint['optimizer_state'])

    epoch = checkpoint['epoch']
    loss = checkpoint['loss']

    print(f"✅ Loaded checkpoint from epoch {epoch} with loss {loss:.4f}")

    return epoch

def train(model, train_loader, optimizer, criterion, start_epoch=0, num_epochs=NUM_EPOCHS, checkpoint_path="checkpoint.pt"):
    for epoch in range(start_epoch, num_epochs):
        model.train()
        epoch_loss = 0
        loop = tqdm(train_loader, desc=f"Epoch [{epoch+1}/{num_epochs}]")

        for src, tgt_input, tgt_output in loop:
            src, tgt_input, tgt_output = src.to(DEVICE), tgt_input.to(DEVICE), tgt_output.to(DEVICE)

            output = model(src, tgt_input, SRC_PAD_IDX, TGT_PAD_IDX)
            output = output.view(-1, output.shape[-1])
            tgt_output = tgt_output.view(-1)

            loss = criterion(output, tgt_output)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()
            loop.set_postfix(loss=loss.item())

        # Save checkpoint at end of each epoch
        save_checkpoint(epoch+1, model, optimizer, epoch_loss / len(train_loader), checkpoint_path)

start_epoch = load_checkpoint(model, optimizer)

train(model, train_loader, optimizer, criterion, start_epoch=start_epoch)

def translate_sentence(model, sentence, en_vocab, hi_vocab, max_len=50):
    model.eval()
    tokens = encode_sentence(sentence, en_vocab, max_len=max_len)
    src_tensor = torch.tensor(tokens).unsqueeze(0).to(DEVICE)

    tgt_tokens = [hi_vocab["<sos>"]]
    for _ in range(max_len):
        tgt_tensor = torch.tensor(tgt_tokens).unsqueeze(0).to(DEVICE)
        with torch.no_grad():
            output = model(src_tensor, tgt_tensor, SRC_PAD_IDX, TGT_PAD_IDX)
        next_token = output[0, -1].argmax().item()
        tgt_tokens.append(next_token)
        if next_token == hi_vocab["<eos>"]:
            break

    translated = [hi_vocab.itos[idx] for idx in tgt_tokens[1:-1]]
    return ' '.join(translated)

example_sentences = [
    "I love you.",
    "What is your name?",
    "How are you?",
    "The weather is nice today.",
    "She is a good teacher."
]

for sentence in example_sentences:
    translation = translate_sentence(model, sentence, en_vocab, hi_vocab)
    print(f"\n🗣 English: {sentence}")
    print(f"🇮🇳 Hindi: {translation}")

import nltk
from nltk.translate.bleu_score import sentence_bleu, corpus_bleu, SmoothingFunction

smoothie = SmoothingFunction().method4

def evaluate_bleu_nltk(model, dataset, en_vocab, hi_vocab, max_len=50):
    references = []
    hypotheses = []

    for en_sentence, hi_sentence in dataset:
        pred = translate_sentence(model, en_sentence, en_vocab, hi_vocab, max_len)
        pred_tokens = pred.split()
        ref_tokens = hi_sentence.split()

        references.append([ref_tokens])   # list of reference lists
        hypotheses.append(pred_tokens)    # list of predicted tokens

    score = corpus_bleu(references, hypotheses, smoothing_function=smoothie)
    print(f"🌐 BLEU Score (NLTK): {score * 100:.2f}")
    return score

val_dataset = [
    ("I love you.", "मैं तुमसे प्यार करता हूँ।"),
    ("How are you?", "आप कैसे हैं?"),
    ("You should sleep.", "आपको सोना चाहिए।"),
    ("Maybe Tom doesn't love you.", "टॉम शायद तुमसे प्यार नहीं करता है।"),
    ("Let me tell Tom.","मुझे टॉम को बताने दीजिए।")
]

evaluate_bleu_nltk(model, val_dataset, en_vocab, hi_vocab)

# Save the model weights
torch.save(model.state_dict(), "transformer_translation_final.pth")

# Save vocab mappings (example using pickle)
import pickle
with open("en_vocab.pkl", "wb") as f:
    pickle.dump(en_vocab, f)

with open("hi_vocab.pkl", "wb") as f:
    pickle.dump(hi_vocab, f)

print("✅ Model and vocabs saved.")

"""#Part-2 and Part-3: Optimizing using Ray Optuna and ASHA Scheduler"""

!pip install ray Optuna

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def load_dataset_tsv(path: str = "English-Hindi.tsv") -> pd.DataFrame:
    df = pd.read_csv(path, sep="\t", header=None, names=["id1", "en", "id2", "hi"])
    df = df[["en", "hi"]].dropna().reset_index(drop=True)
    return df

def explore_dataset(df: pd.DataFrame) -> None:

    print("Total pairs:", len(df))
    df = df.copy()
    df["en_len"] = df["en"].apply(lambda x: len(x.split()))
    df["hi_len"] = df["hi"].apply(lambda x: len(x.split()))

    print("\nEnglish Sentence Length Stats:")
    print(df["en_len"].describe())

    print("\nHindi Sentence Length Stats:")
    print(df["hi_len"].describe())

    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    sns.histplot(df["en_len"], bins=30, kde=True, color="skyblue")
    plt.title("English Sentence Lengths")
    plt.xlabel("Words")

    plt.subplot(1, 2, 2)
    sns.histplot(df["hi_len"], bins=30, kde=True, color="salmon")
    plt.title("Hindi Sentence Lengths")
    plt.xlabel("Words")

    plt.tight_layout()
    plt.show()

    for i in range(min(5, len(df))):
        print(f"EN: {df.loc[i, 'en']}")
        print(f"HI: {df.loc[i, 'hi']}")
        print("---")

def tokenize(sentence):
    return sentence.lower().strip().split()

from collections import Counter
import itertools

class Vocabulary:
    def __init__(self, freq_threshold=2):
        self.freq_threshold = freq_threshold
        self.itos = {0: "<pad>", 1: "<sos>", 2: "<eos>", 3: "<unk>"}
        self.stoi = {"<pad>": 0, "<sos>": 1, "<eos>": 2, "<unk>": 3}
        self.idx = 4

    def build_vocab(self, sentence_list):
        frequencies = Counter()
        for sentence in sentence_list:
            for word in self.tokenize(sentence):
                frequencies[word] += 1

        for word, freq in frequencies.items():
            if freq >= self.freq_threshold:
                self.stoi[word] = self.idx
                self.itos[self.idx] = word
                self.idx += 1

    def tokenize(self, sentence):
        return sentence.lower().strip().split()

    def numericalize(self, sentence):
        tokens = self.tokenize(sentence)
        return [self.stoi.get(token, self.stoi["<unk>"]) for token in tokens]

    def __len__(self):
        return len(self.stoi)

    def __getitem__(self, token):
        return self.stoi.get(token, self.stoi["<unk>"])

# Create vocab instances
def build_vocabs(df: pd.DataFrame, freq_threshold: int = 2) -> tuple["Vocabulary", "Vocabulary"]:
    en_vocab = Vocabulary(freq_threshold=freq_threshold)
    hi_vocab = Vocabulary(freq_threshold=freq_threshold)
    en_vocab.build_vocab(df["en"].tolist())
    hi_vocab.build_vocab(df["hi"].tolist())
    return en_vocab, hi_vocab

def encode_sentence(sentence, vocab, max_len=50):
    tokens = [vocab.stoi["<sos>"]] + vocab.numericalize(sentence)[:max_len-2] + [vocab.stoi["<eos>"]]
    return tokens + [vocab.stoi["<pad>"]] * (max_len - len(tokens))

df_for_vocab = load_dataset_tsv("English-Hindi.tsv")
en_vocab, hi_vocab = build_vocabs(df_for_vocab)

sample_en = "That won't happen."
sample_hi = "वैसा नहीं होगा।"

print("Encoded English:", encode_sentence(sample_en, en_vocab))
print("Encoded Hindi:", encode_sentence(sample_hi, hi_vocab))

import torch
import torch.nn as nn
import math

class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=5000):
        super().__init__()

        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len).unsqueeze(1).float()
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))

        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)

        pe = pe.unsqueeze(0)  # (1, max_len, d_model)
        self.register_buffer('pe', pe)

    def forward(self, x):
        return x + self.pe[:, :x.size(1)]

def scaled_dot_product(q, k, v, mask=None):
    d_k = q.size(-1)
    scores = torch.matmul(q, k.transpose(-2, -1)) / math.sqrt(d_k)

    if mask is not None:
        scores = scores.masked_fill(mask == 0, -1e9)

    attention = torch.softmax(scores, dim=-1)
    return torch.matmul(attention, v), attention

class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, num_heads):
        super(MultiHeadAttention, self).__init__()
        assert d_model % num_heads == 0, "d_model must be divisible by num_heads"

        self.d_model = d_model
        self.num_heads = num_heads
        self.d_k = d_model // num_heads

        self.query_linear = nn.Linear(d_model, d_model)
        self.key_linear = nn.Linear(d_model, d_model)
        self.value_linear = nn.Linear(d_model, d_model)

        self.out_linear = nn.Linear(d_model, d_model)
        self.dropout = nn.Dropout(0.1)

    def forward(self, q, k, v, mask=None):
        batch_size = q.size(0)

        # Project Q, K, V
        Q = self.query_linear(q)  # [B, T, D]
        K = self.key_linear(k)
        V = self.value_linear(v)

        # Reshape and transpose: [B, T, D] -> [B, H, T, Dk]
        Q = Q.view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)  # [B, H, T, Dk]
        K = K.view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)
        V = V.view(batch_size, -1, self.num_heads, self.d_k).transpose(1, 2)

        # Apply scaled dot-product attention
        scores = torch.matmul(Q, K.transpose(-2, -1)) / (self.d_k ** 0.5)

        if mask is not None:
            scores = scores.masked_fill(mask == 0, -1e9)

        attention_weights = torch.softmax(scores, dim=-1)
        attention_output = torch.matmul(self.dropout(attention_weights), V)  # [B, H, T, Dk]

        # Concatenate heads: [B, H, T, Dk] -> [B, T, H * Dk]
        attention_output = attention_output.transpose(1, 2).contiguous() \
                                            .view(batch_size, -1, self.d_model)

        return self.out_linear(attention_output)

class FeedForward(nn.Module):
    def __init__(self, d_model, d_ff=2048, dropout=0.1):
        super().__init__()
        self.linear1 = nn.Linear(d_model, d_ff)
        self.linear2 = nn.Linear(d_ff, d_model)
        self.dropout = nn.Dropout(dropout)
        self.relu = nn.ReLU()

    def forward(self, x):
        return self.linear2(self.dropout(self.relu(self.linear1(x))))

class LayerNorm(nn.Module):
    def __init__(self, d_model, eps=1e-6):
        super().__init__()
        self.gamma = nn.Parameter(torch.ones(d_model))
        self.beta = nn.Parameter(torch.zeros(d_model))
        self.eps = eps

    def forward(self, x):
        mean = x.mean(-1, keepdim=True)
        std = x.std(-1, keepdim=True)
        return self.gamma * (x - mean) / (std + self.eps) + self.beta

class EncoderLayer(nn.Module):
    def __init__(self, d_model, num_heads, d_ff, dropout=0.1):
        super().__init__()
        self.self_attn = MultiHeadAttention(d_model, num_heads)
        self.ffn = FeedForward(d_model, d_ff, dropout)
        self.norm1 = LayerNorm(d_model)
        self.norm2 = LayerNorm(d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, mask=None):
        x = self.norm1(x + self.dropout(self.self_attn(x, x, x, mask)))
        x = self.norm2(x + self.dropout(self.ffn(x)))
        return x

class DecoderLayer(nn.Module):
    def __init__(self, d_model, num_heads, d_ff, dropout=0.1):
        super().__init__()
        self.self_attn = MultiHeadAttention(d_model, num_heads)
        self.cross_attn = MultiHeadAttention(d_model, num_heads)
        self.ffn = FeedForward(d_model, d_ff, dropout)

        self.norm1 = LayerNorm(d_model)
        self.norm2 = LayerNorm(d_model)
        self.norm3 = LayerNorm(d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, enc_out, src_mask=None, tgt_mask=None):
        x = self.norm1(x + self.dropout(self.self_attn(x, x, x, tgt_mask)))
        x = self.norm2(x + self.dropout(self.cross_attn(x, enc_out, enc_out, src_mask)))
        x = self.norm3(x + self.dropout(self.ffn(x)))
        return x

class Encoder(nn.Module):
    def __init__(self, input_vocab_size, d_model, num_layers, num_heads, d_ff, max_len, dropout=0.1):
        super().__init__()
        self.embed = nn.Embedding(input_vocab_size, d_model)
        self.pos_enc = PositionalEncoding(d_model, max_len)
        self.layers = nn.ModuleList([
            EncoderLayer(d_model, num_heads, d_ff, dropout)
            for _ in range(num_layers)
        ])
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, mask=None):
        x = self.embed(x)
        x = self.pos_enc(x)
        x = self.dropout(x)

        for layer in self.layers:
            x = layer(x, mask)

        return x

class Decoder(nn.Module):
    def __init__(self, target_vocab_size, d_model, num_layers, num_heads, d_ff, max_len, dropout=0.1):
        super().__init__()
        self.embed = nn.Embedding(target_vocab_size, d_model)
        self.pos_enc = PositionalEncoding(d_model, max_len)
        self.layers = nn.ModuleList([
            DecoderLayer(d_model, num_heads, d_ff, dropout)
            for _ in range(num_layers)
        ])
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, enc_out, src_mask=None, tgt_mask=None):
        x = self.embed(x)
        x = self.pos_enc(x)
        x = self.dropout(x)

        for layer in self.layers:
            x = layer(x, enc_out, src_mask, tgt_mask)

        return x

class Transformer(nn.Module):
    def __init__(self, src_vocab_size, tgt_vocab_size, d_model=512, num_layers=6, num_heads=8, d_ff=2048, max_len=100, dropout=0.1):
        super().__init__()
        self.encoder = Encoder(src_vocab_size, d_model, num_layers, num_heads, d_ff, max_len, dropout)
        self.decoder = Decoder(tgt_vocab_size, d_model, num_layers, num_heads, d_ff, max_len, dropout)
        self.fc_out = nn.Linear(d_model, tgt_vocab_size)

    def make_pad_mask(self, seq, pad_idx):
        return (seq != pad_idx).unsqueeze(1).unsqueeze(2)  # [B, 1, 1, T]

    def make_subsequent_mask(self, size):
        return torch.tril(torch.ones((size, size))).bool().to(next(self.parameters()).device)

    def forward(self, src, tgt, src_pad_idx, tgt_pad_idx):
        src_mask = self.make_pad_mask(src, src_pad_idx)
        tgt_pad_mask = self.make_pad_mask(tgt, tgt_pad_idx)
        tgt_sub_mask = self.make_subsequent_mask(tgt.size(1))
        tgt_mask = tgt_pad_mask & tgt_sub_mask  # Combine masks

        enc_out = self.encoder(src, src_mask)
        dec_out = self.decoder(tgt, enc_out, src_mask, tgt_mask)

        out = self.fc_out(dec_out)
        return out

from torch.utils.data import Dataset

class TranslationDataset(Dataset):
    def __init__(self, df, en_vocab, hi_vocab, max_len=50):
        self.en_sentences = df["en"].tolist()
        self.hi_sentences = df["hi"].tolist()
        self.en_vocab = en_vocab
        self.hi_vocab = hi_vocab
        self.max_len = max_len

    def __len__(self):
        return len(self.en_sentences)

    def __getitem__(self, idx):
        src = encode_sentence(self.en_sentences[idx], self.en_vocab, self.max_len)
        tgt = encode_sentence(self.hi_sentences[idx], self.hi_vocab, self.max_len)
        return torch.tensor(src), torch.tensor(tgt)

def collate_fn(batch):
    src_batch, tgt_batch = zip(*batch)

    src_batch = torch.stack(src_batch)
    tgt_batch = torch.stack(tgt_batch)

    # Transformer decoder needs: tgt_input (without <eos>) and tgt_output (without <sos>)
    tgt_input = tgt_batch[:, :-1]
    tgt_output = tgt_batch[:, 1:]

    return src_batch, tgt_input, tgt_output

from torch.utils.data import DataLoader

def make_train_loader(
    df: pd.DataFrame,
    en_vocab: Vocabulary,
    hi_vocab: Vocabulary,
    *,
    batch_size: int,
    max_len: int,
) -> DataLoader:
    dataset = TranslationDataset(df, en_vocab, hi_vocab, max_len=max_len)
    return DataLoader(dataset, batch_size=batch_size, shuffle=True, collate_fn=collate_fn)

import torch.nn as nn
import torch.optim as optim
from tqdm import tqdm

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
def build_transformer_from_config(
    config: dict,
    *,
    src_vocab_size: int,
    tgt_vocab_size: int,
    max_len: int,
    device: torch.device,
) -> nn.Module:
    d_model = int(config.get("d_model", 512))
    num_heads = int(config.get("num_heads", 8))
    if d_model % num_heads != 0:
        raise ValueError(f"d_model ({d_model}) must be divisible by num_heads ({num_heads}).")

    model = Transformer(
        src_vocab_size=src_vocab_size,
        tgt_vocab_size=tgt_vocab_size,
        d_model=d_model,
        num_layers=int(config.get("num_layers", 6)),
        num_heads=num_heads,
        d_ff=int(config.get("d_ff", 2048)),
        max_len=max_len,
        dropout=float(config.get("dropout", 0.1)),
    ).to(device)
    return model

import os

def save_checkpoint(epoch, model, optimizer, loss, path="checkpoint.pt"):
    torch.save({
        'epoch': epoch,
        'model_state': model.state_dict(),
        'optimizer_state': optimizer.state_dict(),
        'loss': loss
    }, path)

    print(f"Checkpoint saved at epoch {epoch}, loss {loss:.4f}.")

def load_checkpoint(model, optimizer, path="checkpoint.pt"):
    if torch.cuda.is_available() and path is not None and os.path.exists(path):
        checkpoint = torch.load(path)
    elif path is not None and os.path.exists(path):
        checkpoint = torch.load(path, map_location=torch.device('cpu'))
    else:
        print(f"No checkpoint found at {path}. Starting from scratch.")
        return 0

    model.load_state_dict(checkpoint['model_state'])
    optimizer.load_state_dict(checkpoint['optimizer_state'])

    epoch = checkpoint['epoch']
    loss = checkpoint['loss']

    print(f"✅ Loaded checkpoint from epoch {epoch} with loss {loss:.4f}")

    return epoch

def train(
    model,
    train_loader,
    optimizer,
    criterion,
    *,
    src_pad_idx: int,
    tgt_pad_idx: int,
    device: torch.device,
    start_epoch: int = 0,
    num_epochs: int = 100,
    checkpoint_path: str = "checkpoint.pt",
):
    for epoch in range(start_epoch, num_epochs):
        model.train()
        epoch_loss = 0
        loop = tqdm(train_loader, desc=f"Epoch [{epoch+1}/{num_epochs}]")

        for src, tgt_input, tgt_output in loop:
            src = src.to(device)
            tgt_input = tgt_input.to(device)
            tgt_output = tgt_output.to(device)

            output = model(src, tgt_input, src_pad_idx, tgt_pad_idx)
            output = output.reshape(-1, output.shape[-1]) # Changed .view to .reshape
            tgt_output = tgt_output.reshape(-1) # Changed .view to .reshape

            loss = criterion(output, tgt_output)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()
            loop.set_postfix(loss=loss.item())

        # Save checkpoint at end of each epoch
        save_checkpoint(epoch+1, model, optimizer, epoch_loss / len(train_loader), checkpoint_path)

def train_tune(config: dict) -> None:
    """
    Ray Tune entrypoint.

    Requirements (per assignment):
    - accept a config dict
    - init model/optimizer/criterion from config (no hardcoded globals)
    - report via ray.train.report({"loss": epoch_loss})
    - cap each trial to <= config["max_epochs"]
    """
    # Lazy imports so baseline usage doesn't require Ray.
    from ray import train as ray_train
    from ray import tune

    df = load_dataset_tsv(config.get("data_path", "English-Hindi.tsv"))
    en_vocab, hi_vocab = build_vocabs(df, freq_threshold=int(config.get("freq_threshold", 2)))

    max_len = int(config.get("max_len", 50))
    batch_size = int(config["batch_size"])
    train_loader = make_train_loader(df, en_vocab, hi_vocab, batch_size=batch_size, max_len=max_len)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    src_pad_idx = en_vocab["<pad>"]
    tgt_pad_idx = hi_vocab["<pad>"]

    model = build_transformer_from_config(
        config,
        src_vocab_size=len(en_vocab),
        tgt_vocab_size=len(hi_vocab),
        max_len=max_len,
        device=device,
    )

    criterion = nn.CrossEntropyLoss(ignore_index=tgt_pad_idx)
    optimizer = optim.Adam(model.parameters(), lr=float(config["lr"]))

    max_epochs = int(config.get("max_epochs", 10))

    for epoch in range(max_epochs):
        model.train()
        epoch_loss = 0.0

        for src, tgt_input, tgt_output in train_loader:
            src = src.to(device)
            tgt_input = tgt_input.to(device)
            tgt_output = tgt_output.to(device)

            output = model(src, tgt_input, src_pad_idx, tgt_pad_idx)
            output = output.reshape(-1, output.shape[-1]) # Changed .view to .reshape
            tgt_output = tgt_output.reshape(-1) # Changed .view to .reshape

            loss = criterion(output, tgt_output)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            epoch_loss += float(loss.item())

        epoch_loss = epoch_loss / max(1, len(train_loader))
        tune.report({'loss': epoch_loss, 'epoch': epoch + 1}) # Pass metrics as a dictionary

def translate_sentence(model, sentence, en_vocab, hi_vocab, *, src_pad_idx: int, tgt_pad_idx: int, device: torch.device, max_len=50):
    model.eval()
    tokens = encode_sentence(sentence, en_vocab, max_len=max_len)
    src_tensor = torch.tensor(tokens).unsqueeze(0).to(device)

    tgt_tokens = [hi_vocab["<sos>"]]
    for _ in range(max_len):
        tgt_tensor = torch.tensor(tgt_tokens).unsqueeze(0).to(device)
        with torch.no_grad():
            output = model(src_tensor, tgt_tensor, src_pad_idx, tgt_pad_idx)
        next_token = output[0, -1].argmax().item()
        tgt_tokens.append(next_token)
        if next_token == hi_vocab["<eos>"]:
            break

    translated = [hi_vocab.itos[idx] for idx in tgt_tokens[1:-1]]
    return ' '.join(translated)

import nltk
from nltk.translate.bleu_score import sentence_bleu, corpus_bleu, SmoothingFunction

smoothie = SmoothingFunction().method4

def evaluate_bleu_nltk(model, dataset, en_vocab, hi_vocab, max_len=50):
    references = []
    hypotheses = []

    for en_sentence, hi_sentence in dataset:
        pred = translate_sentence(
            model,
            en_sentence,
            en_vocab,
            hi_vocab,
            src_pad_idx=en_vocab["<pad>"],
            tgt_pad_idx=hi_vocab["<pad>"],
            device=DEVICE,
            max_len=max_len,
        )
        pred_tokens = pred.split()
        ref_tokens = hi_sentence.split()

        references.append([ref_tokens])   # list of reference lists
        hypotheses.append(pred_tokens)    # list of predicted tokens

    score = corpus_bleu(references, hypotheses, smoothing_function=smoothie)
    print(f"🌐 BLEU Score (NLTK): {score * 100:.2f}")
    return score


def run_tune(
    *,
    num_samples: int = 20,
    trial_max_epochs: int = 15,
) -> None:
    """
    Ray Tune + Optuna search with ASHA early stopping.
    Each trial is capped at <= trial_max_epochs epochs (ASHA may stop earlier).
    """
    import ray
    from ray import tune
    from ray import air
    from ray.tune.schedulers import ASHAScheduler
    from ray.tune.search.optuna import OptunaSearch

    # Explicitly initialize Ray with at least 1 CPU to ensure proper resource management
    ray.init(num_cpus=1, num_gpus=1, ignore_reinit_error=True)

    param_space = {
        # Trial cap (Part 3 requirement).
        "max_epochs": trial_max_epochs,
        "data_path": "/content/English-Hindi.tsv", # Updated to absolute path
        "freq_threshold": 2,
        "max_len": 50,
        "d_model": 512,  # keep constant so num_heads choices stay valid

        # Vary >=4 impactful hyperparameters (Part 2.2).
        "lr": tune.loguniform(1e-5, 1e-3),
        "batch_size": tune.choice([16, 32, 64]),
        "num_heads": tune.choice([4, 8]),
        "d_ff": tune.choice([1024, 2048]),
        "dropout": tune.uniform(0.1, 0.4),
    }

    optuna_search = OptunaSearch(metric="loss", mode="min")
    asha = ASHAScheduler(
        metric="loss",
        mode="min",
        max_t=trial_max_epochs,
        grace_period=max(1, min(3, trial_max_epochs // 5)),
        reduction_factor=2,
    )

    tuner = tune.Tuner(
        tune.with_resources(train_tune, resources={"cpu": 1, "gpu": 1}), # Request 1 CPU and 1 GPU for each trial
        tune_config=tune.TuneConfig(
            search_alg=optuna_search,
            scheduler=asha,
            num_samples=num_samples,
        ),
        param_space=param_space,
        run_config=air.RunConfig(name="tune_run")
    )

    results = tuner.fit()
    best = results.get_best_result(metric="loss", mode="min")
    print("\nBest trial:")
    print(best.metrics)
    print(best.config)


def run_baseline_training(
    *,
    num_epochs: int = 100,
    batch_size: int = 60,
    max_len: int = 50,
    lr: float = 1e-4,
    checkpoint_path: str = "checkpoint.pt",
) -> None:
    df = load_dataset_tsv("/content/English-Hindi.tsv")
    en_vocab, hi_vocab = build_vocabs(df, freq_threshold=2)
    train_loader = make_train_loader(df, en_vocab, hi_vocab, batch_size=batch_size, max_len=max_len)

    print(f"Using Device: {DEVICE}")
    src_pad_idx = en_vocab["<pad>"]
    tgt_pad_idx = hi_vocab["<pad>"]

    model = build_transformer_from_config(
        {
            "d_model": 512,
            "num_layers": 6,
            "num_heads": 8,
            "d_ff": 2048,
            "dropout": 0.1,
        },
        src_vocab_size=len(en_vocab),
        tgt_vocab_size=len(hi_vocab),
        max_len=max_len,
        device=DEVICE,
    )

    criterion = nn.CrossEntropyLoss(ignore_index=tgt_pad_idx)
    optimizer = optim.Adam(model.parameters(), lr=lr)

    start_epoch = load_checkpoint(model, optimizer, path=checkpoint_path)
    train(
        model,
        train_loader,
        optimizer,
        criterion,
        src_pad_idx=src_pad_idx,
        tgt_pad_idx=tgt_pad_idx,
        device=DEVICE,
        start_epoch=start_epoch,
        num_epochs=num_epochs,
        checkpoint_path=checkpoint_path,
    )

    example_sentences = [
        "I love you.",
        "What is your name?",
        "How are you?",
        "The weather is nice today.",
        "She is a good teacher.",
    ]
    for sentence in example_sentences:
        translation = translate_sentence(
            model,
            sentence,
            en_vocab,
            hi_vocab,
            src_pad_idx=src_pad_idx,
            tgt_pad_idx=tgt_pad_idx,
            device=DEVICE,
            max_len=max_len,
        )
        print(f"\n🗣 English: {sentence}")
        print(f"🇮🇳 Hindi: {translation}")

    val_dataset = [
        ("I love you.", "मैं तुमसे प्यार करता हूँ।"),
        ("How are you?", "आप कैसे हैं?"),
        ("You should sleep.", "आपको सोना चाहिए।"),
        ("Maybe Tom doesn't love you.", "टॉम शायद तुमसे प्यार नहीं करता है।"),
        ("Let me tell Tom.", "मुझे टॉम को बताने दीजिए."),
    ]
    evaluate_bleu_nltk(model, val_dataset, en_vocab, hi_vocab, max_len=max_len)

    torch.save(model.state_dict(), "transformer_translation_final.pth")

    import pickle
    with open("/content/en_vocab.pkl", "wb") as f:
        pickle.dump(en_vocab, f)
    with open("/content/hi_vocab.pkl", "wb") as f:
        pickle.dump(hi_vocab, f)
    print("✅ Model and vocabs saved.")

#pip install Optuna

if __name__ == "__main__":
    run_tune(num_samples=5, trial_max_epochs=7)

"""## Training with Best Hyperparameters"""

def run_tuned_training(
    num_epochs: int,
    lr: float,
    batch_size: int,
    num_heads: int,
    d_ff: int,
    dropout: float,
    d_model: int = 512,
    num_layers: int = 6,
    max_len: int = 50,
    freq_threshold: int = 2,
    checkpoint_path: str = "transformer_tuned_best.pt",
) -> None:
    print(f"\nStarting training with tuned hyperparameters for {num_epochs} epochs...")
    df = load_dataset_tsv("/content/English-Hindi.tsv")
    en_vocab, hi_vocab = build_vocabs(df, freq_threshold=freq_threshold)
    train_loader = make_train_loader(df, en_vocab, hi_vocab, batch_size=batch_size, max_len=max_len)

    print(f"Using Device: {DEVICE}")
    src_pad_idx = en_vocab["<pad>"]
    tgt_pad_idx = hi_vocab["<pad>"]

    model = build_transformer_from_config(
        {
            "d_model": d_model,
            "num_layers": num_layers,
            "num_heads": num_heads,
            "d_ff": d_ff,
            "dropout": dropout,
        },
        src_vocab_size=len(en_vocab),
        tgt_vocab_size=len(hi_vocab),
        max_len=max_len,
        device=DEVICE,
    )

    criterion = nn.CrossEntropyLoss(ignore_index=tgt_pad_idx)
    optimizer = optim.Adam(model.parameters(), lr=lr)

    start_epoch = load_checkpoint(model, optimizer, path=checkpoint_path)
    train(
        model,
        train_loader,
        optimizer,
        criterion,
        src_pad_idx=src_pad_idx,
        tgt_pad_idx=tgt_pad_idx,
        device=DEVICE,
        start_epoch=start_epoch,
        num_epochs=num_epochs,
        checkpoint_path=checkpoint_path,
    )

    print("\n--- Evaluation on Example Sentences ---")
    example_sentences = [
        "I love you.",
        "What is your name?",
        "How are you?",
        "The weather is nice today.",
        "She is a good teacher.",
    ]
    for sentence in example_sentences:
        translation = translate_sentence(
            model,
            sentence,
            en_vocab,
            hi_vocab,
            src_pad_idx=src_pad_idx,
            tgt_pad_idx=tgt_pad_idx,
            device=DEVICE,
            max_len=max_len,
        )
        print(f"\n🗣 English: {sentence}")
        print(f"🇮🇳 Hindi: {translation}")

    print("\n--- BLEU Score Evaluation ---")
    val_dataset = [
        ("I love you.", "मैं तुमसे प्यार करता हूँ।"),
        ("How are you?", "आप कैसे हैं?"),
        ("You should sleep.", "आपको सोना चाहिए।"),
        ("Maybe Tom doesn't love you.", "टॉम शायद तुमसे प्यार नहीं करता है।"),
        ("Let me tell Tom.", "मुझे टॉम को बताने दीजिए."),
    ]
    evaluate_bleu_nltk(model, val_dataset, en_vocab, hi_vocab, max_len=max_len)

    torch.save(model.state_dict(), "transformer_translation_final_tuned.pth")

    import pickle
    with open("/content/en_vocab_tuned.pkl", "wb") as f:
        pickle.dump(en_vocab, f)
    with open("/content/hi_vocab_tuned.pkl", "wb") as f:
        pickle.dump(hi_vocab, f)
    print("✅ Tuned Model and vocabs saved.")

# Best hyperparameters from Ray Tune output
best_hyperparams_from_tune = {
    'lr': 0.00011079428623002888,
    'batch_size': 32,
    'num_heads': 4,
    'd_ff': 1024,
    'dropout': 0.18271930817849596,
    'd_model': 512,
    'num_layers': 6,
    'max_len': 50,
    'freq_threshold': 2
}

# Run training and evaluation with the best hyperparameters for 90 epochs
run_tuned_training(
    num_epochs=90,
    lr=best_hyperparams_from_tune['lr'],
    batch_size=best_hyperparams_from_tune['batch_size'],
    num_heads=best_hyperparams_from_tune['num_heads'],
    d_ff=best_hyperparams_from_tune['d_ff'],
    dropout=best_hyperparams_from_tune['dropout'],
    d_model=best_hyperparams_from_tune['d_model'],
    num_layers=best_hyperparams_from_tune['num_layers'],
    max_len=best_hyperparams_from_tune['max_len'],
    freq_threshold=best_hyperparams_from_tune['freq_threshold'],
    checkpoint_path="transformer_tuned_best.pt" # Save checkpoint separately
)





